version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - noctx
    - revive
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sakusi4/t5s
